Updated all scripts to work with both V5/V6 robot versions.

diff --git a/scripts/addRobotIds b/scripts/addRobotIds
--- a/scripts/addRobotIds
+++ b/scripts/addRobotIds
@@ -3,7 +3,7 @@
 set -eu
 
 baseDir=$(cd "$(dirname "$(which "$0")")" && pwd)
-bhDir=$(dirname "${baseDir}")
+tnDir=$(dirname "${baseDir}")
 includeDir="${baseDir}/Include/"
 
 source "${includeDir}/bhumanBase"
@@ -12,17 +12,19 @@ remoteIp=""
 headId=""
 bodyId=""
 name=""
+version=""
 
 usage() {
   echo "usage:"
   echo "${0} [-h]"
   echo "${0} -ids <headId> <BodyId> <name>"
-  echo "${0} -ip <remoteIp> <name>"
+  echo "${0} -ip <remoteIp> <version> <name>"
   echo ""
   echo " <name>     : Name of the robot."
   echo " <headId>   : The id of the robots head."
   echo " <bodyId>   : The id of the robots body."
   echo " <remoteIp> : The id of the robots body."
+  echo " <version> : The version of the robot."
   echo ""
   echo " -ids       : Uses the the provided ids."
   echo " -ip        : Loads the ids from the robot with the provided ip."
@@ -37,13 +39,10 @@ parseOptions() {
       bodyId=${3}
       name=${4}
       return 0
-    else
-      usage
-    fi
-  elif [ $# -eq 3 ]; then
-    if [ ${1} == "-ip" ]; then
+    elif [ ${1} == "-ip" ]; then
       remoteIp=${2}
-      name=${3}
+      version=${3}
+      name=${4}
       return 1
     else
       usage
@@ -60,8 +59,8 @@ getIdsFromRobot() {
   tmpPath="/tmp/NaoInstall"
   ssh -i "${privateKey}" ${sshOptions} nao@${remoteIp} "rm -Rf ${tmpPath}" || fatal "Can't remove '${tmpPath}' on NAO"
   ssh -i "${privateKey}" ${sshOptions} nao@${remoteIp} "mkdir -p ${tmpPath}" || fatal "Can't create '${tmpPath}' on NAO"
-  rsync ${rsyncOptions} -e "${sshCommand}" "${fileDir}/bin/getHeadId-V6.py" nao@${remoteIp}:${tmpPath}/getHeadId.py || fatal "Can't copy 'getHeadId.py' to NAO"
-  rsync ${rsyncOptions} -e "${sshCommand}" "${fileDir}/bin/getBodyId-V6.py" nao@${remoteIp}:${tmpPath}/getBodyId.py || fatal "Can't copy 'getBodyId.py' to NAO"
+  rsync ${rsyncOptions} -e "${sshCommand}" "${binDir}/${version}/getHeadId.py" nao@${remoteIp}:${tmpPath}/getHeadId.py || fatal "Can't copy 'getHeadId.py' to NAO"
+  rsync ${rsyncOptions} -e "${sshCommand}" "${binDir}/${version}/getBodyId.py" nao@${remoteIp}:${tmpPath}/getBodyId.py || fatal "Can't copy 'getBodyId.py' to NAO"
 
   # get headId
   headId=$(ssh -i "${privateKey}" ${sshOptions} nao@${remoteIp} "bash -l -c 'python /tmp/NaoInstall/getHeadId.py' | grep -vE '\[(W|I)\]'")
diff --git a/scripts/copyFiles b/scripts/copyFiles
--- a/scripts/copyFiles
+++ b/scripts/copyFiles
@@ -12,16 +12,16 @@ ROBOT=""
 IP_PREFIX="192.168.30"
 WLAN_PREFIX="10.0.30"
 ROBOT_VERSION="V5"
+TOOLCHAIN="cross"
 
 usage()
 {
     echo "Usage:"
-    echo "./install_robot.sh -b=<BUILD> -t=<TOOLCHAIN> -r=<ROBOT> -f=<FILES> -w"
+    echo "./copyFiles -b=<BUILD> -r=<ROBOT> -f=<FILES> -w"
     echo ""
     echo " -h | --help : Displays the help"
     echo " -b | --build : Build type (Release/Debug/Release-Motion)"
-    echo " -t | --tool-chain : Toolchain name used in code compilation (" $TOOLCHAIN ")"
-    echo " -r | --robot : Name of the robot for which calibration is needed (" Nu-<ROBOT_NUMBER> ")"
+    echo " -r | --robot : Name of the robot ( Nu-<ROBOT_NUMBER> )"
     echo " -f | --files: Files to be copied on to the robot (ALL/DEPENDS/CONFIG/LIBS)"
     echo " -w | --robot : If the robot is connected through the lan network"
     echo " -rv | --robot-version : V5 or V6 robot"
@@ -73,10 +73,6 @@ if [ "$FILES" = "" ]; then
   FILES="ALL"
 fi
 
-if [ "$TOOLCHAIN" = "" ]; then
-  TOOLCHAIN="cross"
-fi
-
 PREFIX="${ROBOT:0:3}"
 NUMBER_LEN=`expr 3 + ${#ROBOT} - 3`
 ROBOT_NUM="${ROBOT:3:${NUMBER_LEN}}"
@@ -110,18 +106,17 @@ ssh -i "${privateKey}" ${sshOptions} nao@$IP_PREFIX.$ROBOT_NUM "mkdir -p ${LIB_T
 ssh -i "${privateKey}" ${sshOptions} nao@$IP_PREFIX.$ROBOT_NUM "mkdir -p ${CONFIG_TARGET}" || fatal "Can't create '${CONFIG_TARGET}' on NAO"
 ssh -i "${privateKey}" ${sshOptions} nao@$IP_PREFIX.$ROBOT_NUM "mkdir -p ${LOGS_TARGET}" || fatal "Can't create '${LOGS_TARGET}' on NAO"
 
-ROBOT_DIR=$PATH_TO_TEAM_NUST_DIR/config/Robots/Nu-1$ROBOT_NUM
+ROBOT_DIR=$PATH_TO_TEAM_NUST_DIR/config/Robots/Nu-$ROBOT_NUM
 CROSS_DEPENDS_DIR=$PATH_TO_TEAM_NUST_DIR/cross-depends
 BUILD_DIR=$PATH_TO_TEAM_NUST_DIR/build-$ROBOT_VERSION/$BUILD/$TOOLCHAIN/lib
 echo $BUILD_DIR
 if [ "$FILES" = "ALL" ]; then
-  # Copy naoqi config over to the robot
-  rsync ${rsyncOptions} -e "${sshCommand}" ./Files/* nao@$IP_PREFIX.$ROBOT_NUM:${FILES_TARGET} || fatal "Can't copy to '${FILES_TARGET}' on NAO"
   # Copy configuration files to the robot 
   rsync ${rsyncOptions} -e "${sshCommand}" $ROBOT_DIR/* nao@$IP_PREFIX.$ROBOT_NUM:${CONFIG_TARGET} || fatal "Can't copy to '${CONFIG_TARGET}' on NAO"
   rsync ${rsyncOptions} -e "${sshCommand}" $ROBOT_DIR/../../BehaviorConfigs nao@$IP_PREFIX.$ROBOT_NUM:${CONFIG_TARGET} || fatal "Can't copy to '${CONFIG_TARGET}' on NAO"
   rsync ${rsyncOptions} -e "${sshCommand}" $ROBOT_DIR/../../Common/* nao@$IP_PREFIX.$ROBOT_NUM:${CONFIG_TARGET} || fatal "Can't copy to '${CONFIG_TARGET}' on NAO"
   rsync ${rsyncOptions} -e "${sshCommand}" $ROBOT_DIR/../../Keys nao@$IP_PREFIX.$ROBOT_NUM:${CONFIG_TARGET} || fatal "Can't copy to '${CONFIG_TARGET}' on NAO"
+  rsync ${rsyncOptions} -e "${sshCommand}" Files/* nao@$IP_PREFIX.$ROBOT_NUM:${FILES_TARGET} || fatal "Can't copy to '${FILES_TARGET}' on NAO"
   if [ "$ROBOT_VERSION" = "V5" ]; then
   # Copy camera driver if it is V5 robot
   rsync ${rsyncOptions} -e "${sshCommand}" $PATH_TO_TEAM_NUST_DIR/bkernel-modules/mt9m114.ko nao@$IP_PREFIX.$ROBOT_NUM:${DEPENDS_TARGET}
diff --git a/scripts/installRobot b/scripts/installRobot
--- a/scripts/installRobot
+++ b/scripts/installRobot
@@ -3,32 +3,34 @@
 set -eu
 
 baseDir="$(cd "$(dirname "$(which "$0")")" && pwd)"
-bhDir="$(dirname "${baseDir}")"
+tnDir="$(dirname "${baseDir}")"
 includeDir="${baseDir}/Include/"
 
 source "${includeDir}/bhumanBase"
 
 headName=""
-robotVersion=""
+version=""
 
 usage() {
   echo "usage:"
-  echo "${0} <ipaddress>"
+  echo "${0} <version> <ipaddress>"
   echo ""
   echo " <address> : the current dns name or ip address of the robot to install"
+  echo " <version> : robot version"
   echo " -h|--help : displays this help"
   exit 1
 }
 
 parseOptions() {
   # -h or --help => print help
-  if [ $# -ne 1 ] ; then
-    if [ $# -gt 1 ] ; then
+  if [ $# -ne 2 ] ; then
+    if [ $# -gt 2 ] ; then
       error "Too many arguments!"
     fi
     usage
   fi
-  robotIp=${1}
+  version=${1}
+  robotIp=${2}
 
   # try to ping robot
   if [ `ping ${pingoptions} ${robotIp} > /dev/null && echo 1 || echo 0` == "0" ]; then
@@ -47,7 +49,7 @@ getNames() {
   tmpPath="/tmp/NaoInstall"
   ssh -i "${privateKey}" ${sshOptions} nao@${robotIp} "rm -Rf ${tmpPath}" || fatal "Can't remove '${tmpPath}' on NAO"
   ssh -i "${privateKey}" ${sshOptions} nao@${robotIp} "mkdir -p ${tmpPath}" || fatal "Can't create '${tmpPath}' on NAO"
-  rsync ${rsyncOptions} -e "${sshCommand}" "${fileDir}/bin/getHeadId-V6.py" nao@${robotIp}:${tmpPath}/getHeadId.py || fatal "Can't copy 'getHeadId.py' to NAO"
+  rsync ${rsyncOptions} -e "${sshCommand}" "${binDir}/${version}/getHeadId.py" nao@${robotIp}:${tmpPath}/getHeadId.py || fatal "Can't copy 'getHeadId.py' to NAO"
 
   # get headId
   local headId
@@ -100,6 +102,8 @@ copyFiles() {
 
   ssh -i "${privateKey}" ${sshOptions} nao@${robotIp} "mkdir -p ${copyTo}" || fatal "Can't create '${copyTo}' on NAO"
   rsync ${rsyncOptions} -e "${sshCommand}" "${fileDir}"/* nao@${robotIp}:${copyTo} || fatal "Can't copy to '${copyTo}' on NAO"
+  rsync ${rsyncOptions} -e "${sshCommand}" "${fileDir}/${version}"/* nao@${robotIp}:${copyTo} || fatal "Can't copy to '${copyTo}' on NAO"
+  rsync ${rsyncOptions} -e "${sshCommand}" "${binDir}"/* nao@${robotIp}:${copyTo}/bin || fatal "Can't copy to '${copyTo}' on NAO"
   rsync ${rsyncOptions} -e "${sshCommand}" "${robotDir}"/* nao@${robotIp}:${copyTo}/Robot/ || fatal "Can't copy to '${copyTo}/Robot' on NAO"
   rsync ${rsyncOptions} -e "${sshCommand}" "${baseDir}/Network/Profiles" nao@${robotIp}:${copyTo}/Robot/ || fatal "Can't copy to '${copyTo}/Robot' on NAO"
 }
